# Generated by Django 5.2.1 on 2025-05-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='room_photos/'),
        ),
    ]
