# Generated by Django 4.2.21 on 2025-06-30 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0004_equipment_remove_room_room_type_booking_equipments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Note de 1 à 5')),
                ('comment', models.TextField(blank=True, help_text="Commentaire de l'utilisateur", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(help_text='Réservation associée à cet avis', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='booking.booking')),
                ('user', models.ForeignKey(help_text="Utilisateur qui a laissé l'avis", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-created_at'],
            },
        ),
    ]
